import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { FaLightbulb, FaQuestionCircle, FaRobot, FaArrowLeft } from 'react-icons/fa';
import './TopicPage.css';

// Mock data - in a real app, this would come from an API
const topicData: Record<string, any> = {
  'aptitude': {
    'percentage': {
      name: 'Percentage',
      formulas: [
        'Percentage = (Part/Whole) × 100',
        'If the price of an item increases by x%, then the reduction in consumption so that expenditure remains the same is: (x/(100 + x)) × 100%',
        'If the price of an item decreases by x%, then the increase in consumption so that expenditure remains the same is: (x/(100 - x)) × 100%'
      ],
      tips: [
        'To find x% of a number, multiply the number by x/100',
        'To calculate percentage increase/decrease: ((New Value - Original Value) / Original Value) × 100%',
        'For successive percentage changes, multiply the individual percentages (as decimals) and convert back to percentage'
      ],
      questions: Array(12).fill(0).map((_, i) => ({
        id: i + 1,
        text: `If the price of a product increases from $${20 + i * 5} to $${25 + i * 5}, what is the percentage increase?`,
        options: [
          `${20 + i}%`,
          `${25 + i}%`,
          `${15 + i}%`,
          `${10 + i}%`
        ],
        correctAnswer: 0,
        explanation: `The increase is $${5} on $${20 + i * 5}, so the percentage increase is (5 / (${20 + i * 5})) × 100 = ${Math.round((5 / (20 + i * 5)) * 100)}%`
      }))
    },
    // Add more aptitude topics as needed
  },
  'reasoning': {
    'number-series': {
      name: 'Number Series',
      formulas: [
        'Arithmetic Progression: a, a + d, a + 2d, a + 3d, ...',
        'Geometric Progression: a, ar, ar², ar³, ...',
        'Fibonacci Series: 0, 1, 1, 2, 3, 5, 8, 13, ...'
      ],
      tips: [
        'Look for patterns in differences between consecutive numbers',
        'Check for multiplication or division patterns',
        'Look for alternating patterns in complex series',
        'Check for squares, cubes, or other powers'
      ],
      questions: Array(12).fill(0).map((_, i) => ({
        id: i + 1,
        text: `What is the next number in the series: 2, 4, 8, 16, ...?`,
        options: [
          '24',
          '32',
          '30',
          '28'
        ],
        correctAnswer: 1,
        explanation: 'Each number is multiplied by 2 to get the next number: 2×2=4, 4×2=8, 8×2=16, so 16×2=32.'
      }))
    },
    // Add more reasoning topics as needed
  }
};

const TopicPage: React.FC = () => {
  const { subject, topicId } = useParams<{ subject: string; topicId: string }>();
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState<'formulas' | 'tips' | 'questions'>('formulas');
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [showSolution, setShowSolution] = useState(false);
  const [selectedOption, setSelectedOption] = useState<number | null>(null);
  const [showAIFormulas, setShowAIFormulas] = useState(false);
  const [aiQuestion, setAiQuestion] = useState('');
  const [aiResponse, setAiResponse] = useState('');
  const [loadingAI, setLoadingAI] = useState(false);

  if (!subject || !topicId || !topicData[subject]?.[topicId]) {
    return <div className="not-found">Topic not found</div>;
  }

  const topic = topicData[subject][topicId];
  const questions = topic.questions || [];

  const handleNextQuestion = () => {
    if (currentQuestion < questions.length - 1) {
      setCurrentQuestion(currentQuestion + 1);
      setShowSolution(false);
      setSelectedOption(null);
    }
  };

  const handlePreviousQuestion = () => {
    if (currentQuestion > 0) {
      setCurrentQuestion(currentQuestion - 1);
      setShowSolution(false);
      setSelectedOption(null);
    }
  };

  const handleGenerateMoreQuestions = () => {
    // In a real app, this would fetch more questions from an API
    alert('In a real app, this would generate 5 more questions');
  };

  const handleAISubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!aiQuestion.trim()) return;
    
    setLoadingAI(true);
    // In a real app, this would call an AI API
    setTimeout(() => {
      setAiResponse(`This is a simulated response to: "${aiQuestion}". In a real application, this would be generated by an AI service.`);
      setLoadingAI(false);
    }, 1000);
  };

  return (
    <div className="topic-page">
      <button className="back-button" onClick={() => navigate(-1)}>
        <FaArrowLeft /> Back to {subject.charAt(0).toUpperCase() + subject.slice(1)}
      </button>
      
      <h1>{topic.name}</h1>
      
      <div className="tabs">
        <button 
          className={`tab ${activeTab === 'formulas' ? 'active' : ''}`}
          onClick={() => setActiveTab('formulas')}
        >
          <FaLightbulb /> Formulas
        </button>
        <button 
          className={`tab ${activeTab === 'tips' ? 'active' : ''}`}
          onClick={() => setActiveTab('tips')}
        >
          <FaLightbulb /> Tips
        </button>
        <button 
          className={`tab ${activeTab === 'questions' ? 'active' : ''}`}
          onClick={() => setActiveTab('questions')}
        >
          <FaQuestionCircle /> Practice Questions
        </button>
      </div>
      
      <div className="tab-content">
        {activeTab === 'formulas' && (
          <div className="formulas-section">
            <h2>Important Formulas</h2>
            <ul className="formulas-list">
              {topic.formulas.map((formula: string, index: number) => (
                <li key={index} className="formula-item">
                  {formula}
                  <button 
                    className="ai-explain-btn"
                    onClick={() => {
                      setShowAIFormulas(true);
                      setAiQuestion(`Can you explain this formula: ${formula}?`);
                    }}
                  >
                    <FaRobot /> Explain
                  </button>
                </li>
              ))}
            </ul>
            
            <div className="ai-assistant">
              <h3>AI Formula Assistant</h3>
              <form onSubmit={handleAISubmit}>
                <input
                  type="text"
                  value={aiQuestion}
                  onChange={(e) => setAiQuestion(e.target.value)}
                  placeholder="Ask a question about any formula..."
                  className="ai-input"
                />
                <button type="submit" className="ai-submit" disabled={loadingAI}>
                  {loadingAI ? 'Thinking...' : 'Ask AI'}
                </button>
              </form>
              
              {aiResponse && (
                <div className="ai-response">
                  <h4>AI Response:</h4>
                  <p>{aiResponse}</p>
                </div>
              )}
            </div>
          </div>
        )}
        
        {activeTab === 'tips' && (
          <div className="tips-section">
            <h2>Tips & Tricks</h2>
            <ul className="tips-list">
              {topic.tips.map((tip: string, index: number) => (
                <li key={index} className="tip-item">
                  {tip}
                </li>
              ))}
            </ul>
          </div>
        )}
        
        {activeTab === 'questions' && questions.length > 0 && (
          <div className="questions-section">
            <div className="question-navigation">
              <button 
                onClick={handlePreviousQuestion} 
                disabled={currentQuestion === 0}
                className="nav-button"
              >
                Previous
              </button>
              <span>Question {currentQuestion + 1} of {questions.length}</span>
              <button 
                onClick={handleNextQuestion} 
                disabled={currentQuestion === questions.length - 1}
                className="nav-button"
              >
                Next
              </button>
            </div>
            
            <div className="question-card">
              <h3>Question {currentQuestion + 1}</h3>
              <p>{questions[currentQuestion].text}</p>
              
              <div className="options">
                {questions[currentQuestion].options.map((option: string, index: number) => (
                  <div 
                    key={index}
                    className={`option ${
                      selectedOption === index 
                        ? showSolution 
                          ? index === questions[currentQuestion].correctAnswer 
                            ? 'correct' 
                            : 'incorrect'
                          : 'selected'
                        : ''
                    }`}
                    onClick={() => !showSolution && setSelectedOption(index)}
                  >
                    {String.fromCharCode(65 + index)}. {option}
                  </div>
                ))}
              </div>
              
              {!showSolution ? (
                <button 
                  className="solution-button" 
                  onClick={() => selectedOption !== null && setShowSolution(true)}
                  disabled={selectedOption === null}
                >
                  Check Answer
                </button>
              ) : (
                <div className="solution">
                  <h4>Explanation:</h4>
                  <p>{questions[currentQuestion].explanation}</p>
                  <button 
                    className="ai-explain-btn"
                    onClick={() => {
                      setShowAIFormulas(true);
                      setAiQuestion(`Can you explain this solution: ${questions[currentQuestion].explanation}?`);
                    }}
                  >
                    <FaRobot /> Ask AI to Explain
                  </button>
                </div>
              )}
            </div>
            
            <button 
              className="generate-more-btn"
              onClick={handleGenerateMoreQuestions}
            >
              Generate 5 More Questions
            </button>
          </div>
        )}
      </div>
      
      {/* AI Chat Modal */}
      {showAIFormulas && (
        <div className="ai-chat-modal">
          <div className="ai-chat-content">
            <div className="ai-chat-header">
              <h3>AI Assistant</h3>
              <button onClick={() => setShowAIFormulas(false)}>×</button>
            </div>
            <div className="ai-chat-messages">
              {aiQuestion && (
                <div className="user-message">
                  <strong>You:</strong> {aiQuestion}
                </div>
              )}
              {aiResponse && (
                <div className="ai-message">
                  <strong>AI:</strong> {aiResponse}
                </div>
              )}
              {loadingAI && <div className="ai-loading">AI is thinking...</div>}
            </div>
            <form onSubmit={handleAISubmit} className="ai-chat-input">
              <input
                type="text"
                value={aiQuestion}
                onChange={(e) => setAiQuestion(e.target.value)}
                placeholder="Ask a question..."
              />
              <button type="submit" disabled={loadingAI}>
                {loadingAI ? 'Sending...' : 'Send'}
              </button>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default TopicPage;
